-- Market Radar: compact generated-candidate persistence
-- Safe to run multiple times.
-- Run in Supabase SQL Editor before enabling the app-side write path in production.

create table if not exists public.ml_generated_candidates (
    id bigint generated by default as identity primary key,
    snapshot_poll_ts timestamptz not null,
    session_date date,
    recommendation_id text,
    quality_tag text,
    decision_source text,
    candidate_id text not null,
    lane text,
    index_key text,
    strategy_type text,
    trade_mode text,
    rank integer,
    watchlist_rank integer,
    was_surfaced boolean not null default false,
    net_premium double precision,
    max_profit double precision,
    max_loss double precision,
    risk_reward double precision,
    premium_edge double precision,
    ev_per_1k double precision,
    est_cost double precision,
    capital_blocked boolean,
    width integer,
    expiry text,
    sigma_otm double precision,
    iv_richness double precision,
    credit_width_ratio double precision,
    is_credit boolean,
    execution_ready boolean,
    execution_gate text,
    entry_action text,
    direction_safe boolean,
    brain_score double precision,
    p_ml double precision,
    ml_action text,
    ml_edge double precision,
    ml_regime text,
    ml_unsure boolean,
    ml_ood_flag boolean,
    signal_independence_score double precision,
    generated_count integer,
    watchlist_count integer,
    created_at timestamptz not null default now()
);

create unique index if not exists idx_ml_generated_candidates_poll_candidate
    on public.ml_generated_candidates (snapshot_poll_ts, candidate_id);

create index if not exists idx_ml_generated_candidates_session_date
    on public.ml_generated_candidates (session_date);

create index if not exists idx_ml_generated_candidates_lane
    on public.ml_generated_candidates (lane);

create index if not exists idx_ml_generated_candidates_strategy
    on public.ml_generated_candidates (strategy_type);

create index if not exists idx_ml_generated_candidates_surfaced
    on public.ml_generated_candidates (was_surfaced, watchlist_rank);

create index if not exists idx_ml_generated_candidates_session_lane
    on public.ml_generated_candidates (session_date, lane, was_surfaced);

-- Verification: table shape
select table_name, column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and table_name = 'ml_generated_candidates'
order by ordinal_position;

-- Verification: indexes
select indexname, indexdef
from pg_indexes
where schemaname = 'public'
  and tablename = 'ml_generated_candidates'
order by indexname;

